[project]
name = "moncoder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.9.0",
    "beautifulsoup4>=4.14.0",
    "google-auth>=2.40.3",
    "html2text>=2025.4.15",
    "litellm>=1.78.3",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
    "ruff>=0.13.2",
    "textual>=6.1.0",
    "xdg-base-dirs>=6.0.2",
]
